// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/home/app-header.vue')['default']
    Apply: typeof import('./components/Apply.vue')['default']
    Banner: typeof import('./components/home/banner.vue')['default']
    BlockTitle: typeof import('./components/home/block-title.vue')['default']
    College: typeof import('./components/skill/college.vue')['default']
    CommonBanner: typeof import('./components/common-banner.vue')['default']
    CompanyCuture: typeof import('./components/about/company-cuture.vue')['default']
    CompanyProfile: typeof import('./components/about/company-profile.vue')['default']
    CompanyQualification: typeof import('./components/about/company-qualification.vue')['default']
    Contact: typeof import('./components/about/contact.vue')['default']
    ContactUs: typeof import('./components/home/contact-us.vue')['default']
    ContentTitle: typeof import('./components/common/content-title.vue')['default']
    CountUp: typeof import('./components/CountUp.vue')['default']
    Dietician: typeof import('./components/profession/health/dietician.vue')['default']
    Education: typeof import('./components/home/education.vue')['default']
    Employment: typeof import('./components/skill/employment.vue')['default']
    English: typeof import('./components/profession/MA/english.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HighLight: typeof import('./components/common/HighLight.vue')['default']
    ImageText: typeof import('./components/career/ImageText.vue')['default']
    International: typeof import('./components/profession/MA/international.vue')['default']
    Introduction: typeof import('./components/skill/introduction.vue')['default']
    Invite: typeof import('./components/skill/invite.vue')['default']
    Nav: typeof import('./components/profession/digital/nav.vue')['default']
    OurStrength: typeof import('./components/home/our-strength.vue')['default']
    Profession: typeof import('./components/home/profession.vue')['default']
    Project: typeof import('./components/home/project.vue')['default']
    Skill: typeof import('./components/home/skill.vue')['default']
    SkillTitle: typeof import('./components/skill-title.vue')['default']
    Tcm: typeof import('./components/profession/health/tcm.vue')['default']
    Technology: typeof import('./components/profession/health/technology.vue')['default']
    TelNumber: typeof import('./components/TelNumber.vue')['default']
    Thailand: typeof import('./components/profession/MA/thailand.vue')['default']
    Title1: typeof import('./components/common/Title1.vue')['default']
    Title2: typeof import('./components/common/Title2.vue')['default']
    ToTop: typeof import('./components/ToTop.vue')['default']
  }
}

export { }
